### PR TITLE
Redirect users primarily to back_url/referer if present (usage: mail …

### PR DESCRIPTION
**Pull request by addow**
Redirect users primarily to back_url/referer if present (usage: mail or external link), otherwise to default My Page.

### CODE REVIEW

**Comment by jmlagace** [comment]
Hi @addow, thanks for the pull request. 

Accepting the change as-is would break the use case completely as the referrer will always be present when navigating through the Redmine. I'm thinking a configuration would be appropriate to have the end user choose the expected behaviour.

If you don't want to wait, can you add the configuration page for the plugin? Otherwise I will merge it but add a plugin configuration at a later point in time.

Thanks!

**Comment by addow** [comment]
Hi @jmlagace,

Sorry if the PR broke the use case. Then I have misinterpreted the use case of the plugin. I had the feeling and got quite some situations were people clicked on a link in an email (unauthorized) or external tool, then first they were redirected to the login form and afterwards always end up on the "My Page", whilst they were expecting to go back to the initially clicked link (from the email).

Good idea and quite obvious then to create a plugin config page were you decide the functionality for yourself. I'll first test this with another plugin I found minutes ago before implementing it.

**Comment by jmlagace** [comment]
@addow I assume you have found another plugin that works better for your use case? I'll close the pull request if that's the case.

**Comment by addow** [comment]
@jmlagace correct. Replaced it with some custom code. Issue can be closed.

**Pull request closed without merging**
